stages:
  train_risk_map:
    cmd: python src/train_kmed.py
    deps:
      - src/train_kmed.py
      - data/raw
    outs:
      - app/ml/kmeans/static
      - app/ml/kmed/static

  train_realtime:
    cmd: python src/train_realtime.py
    deps:
      - src/train_realtime.py
      - src/realtime_helpers.py
      - data/raw/bmkg_raw.csv
      - data/raw/gadm41_IDN_2.json
    outs:
      - data/processed/raw_features_realtime.csv
      - data/processed/kabupaten_boundaries.json
      - app/ml/kmeans/realtime
      - app/ml/kmed/realtime