"""autogenerate models vs db

Revision ID: d6f588e2c016
Revises: 0001_initial
Create Date: 2026-06-13 00:43:29.064170
"""

"""Autogenerated migration comparing models vs DB (adjusted for safety)."""

# pylint: disable=E1101,no-member

from alembic import op
from typing import Any, cast
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# Cast `op` to Any to avoid linter complaints about dynamic Alembic API.
op = cast(Any, op)

revision = 'd6f588e2c016'
down_revision = '0001_initial'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - adjusted for safety ###
    # Guard operations that reference legacy tables which may not exist in
    # fresh databases. If the table is present apply the change; otherwise
    # skip non-destructive adjustments.
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if inspector.has_table('dibi_earthquakes_raw'):
        # Add nullable `uid` so existing rows are not rejected. Backfill and
        # stricter constraints should be added in follow-up migrations.
        op.add_column('dibi_earthquakes_raw', sa.Column('uid', sa.UUID(), nullable=True))
    else:
        # Table is absent (e.g. new DB); skip this non-critical change.
        pass

    # No other destructive changes applied automatically.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dibi_earthquakes_raw', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('dibi_earthquakes_raw', sa.Column('kejadian', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dibi_earthquakes_raw', type_='unique')
    op.alter_column('dibi_earthquakes_raw', 'fasum_rusak',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dibi_earthquakes_raw', 'rumah_terendam',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dibi_earthquakes_raw', 'rumah_rusak',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dibi_earthquakes_raw', 'korban_terluka',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dibi_earthquakes_raw', 'korban_hilang',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dibi_earthquakes_raw', 'korban_meninggal',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dibi_earthquakes_raw', 'provinsi',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('dibi_earthquakes_raw', 'kabupaten',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('dibi_earthquakes_raw', 'lokasi',
               existing_type=sa.TEXT(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('dibi_earthquakes_raw', 'tanggal_kejadian',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('dibi_earthquakes_raw', 'id_kabupaten',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dibi_earthquakes_raw', 'kode_identitas_bencana',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('dibi_earthquakes_raw', 'uid')
    op.create_table('region_risk_enriched',
    sa.Column('id_kabupaten', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('nama_kabupaten', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cluster_label', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('jumlah_gempa', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('avg_magnitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('max_magnitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('avg_depth', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('korban_total', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rumah_rusak_total', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('fasum_rusak_total', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('city_geojsn',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('geometry', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('city_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('province_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('province_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('province_name_local', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city_alt_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city_name_local', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city_type_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city_cc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city_hasc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('gadm41_IDN_2_pkey'))
    )
    op.create_table('bmkg_raw',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('magnitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mag_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('depth_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('phase_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('azimuth_gap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agency', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bmkg_raw_pkey'))
    )
    # ### end Alembic commands ###
